#!/usr/bin/env bash
# Local IsaacLab launcher for ESROBO body-tracking UDP teleoperation.

set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
ISAACLAB_DIR="${ROOT_DIR}/external/IsaacLab"
ISAACLAB_ENV_NAME="${ISAACLAB_ENV_NAME:-env_isaaclab}"

DEVICE="${DEVICE:-cuda:0}"
TASK="${TASK:-DualArmTeleop-ESROBO-RobotOnly-BimanualIK-Abs-v0}"
ESROBO_BODY_UDP_HOST="${ESROBO_BODY_UDP_HOST:-0.0.0.0}"
ESROBO_BODY_UDP_PORT="${ESROBO_BODY_UDP_PORT:-15050}"
ESROBO_BODY_SWAP_LEFT_RIGHT_TARGETS="${ESROBO_BODY_SWAP_LEFT_RIGHT_TARGETS:-0}"
ESROBO_BODY_USE_WAIST_FRAME="${ESROBO_BODY_USE_WAIST_FRAME:-0}"
ESROBO_BODY_POSITION_DELTA_SIGNS="${ESROBO_BODY_POSITION_DELTA_SIGNS:-1 1 1}"
ESROBO_BODY_RETARGETING_MODE="${ESROBO_BODY_RETARGETING_MODE:-arm_vector}"
ESROBO_BODY_ARM_VECTOR_POSITION_MODE="${ESROBO_BODY_ARM_VECTOR_POSITION_MODE:-segment_direction_absolute}"
ESROBO_ENABLE_ELBOW_IK_TASKS="${ESROBO_ENABLE_ELBOW_IK_TASKS:-1}"
ESROBO_WRIST_ONLY_IK="${ESROBO_WRIST_ONLY_IK:-0}"
ESROBO_BODY_REQUIRE_CALIBRATION="${ESROBO_BODY_REQUIRE_CALIBRATION:-0}"
ESROBO_BODY_AUTO_START_REFERENCE="${ESROBO_BODY_AUTO_START_REFERENCE:-0}"
ESROBO_BODY_AUTO_START_REFERENCE_DELAY_S="${ESROBO_BODY_AUTO_START_REFERENCE_DELAY_S:-2.0}"
ESROBO_BODY_AUTO_START_REFERENCE_SAMPLE_START_S="${ESROBO_BODY_AUTO_START_REFERENCE_SAMPLE_START_S:-0.75}"
ESROBO_BODY_AUTO_START_REFERENCE_MAX_STD_M="${ESROBO_BODY_AUTO_START_REFERENCE_MAX_STD_M:-0.05}"
ESROBO_BODY_AUTO_START_REFERENCE_MIN_SAMPLES="${ESROBO_BODY_AUTO_START_REFERENCE_MIN_SAMPLES:-5}"
ESROBO_BODY_AUTO_START_REFERENCE_REQUIRE_WAIST="${ESROBO_BODY_AUTO_START_REFERENCE_REQUIRE_WAIST:-1}"
ESROBO_BODY_ARM_VECTOR_MAX_REACH="${ESROBO_BODY_ARM_VECTOR_MAX_REACH:-0.72}"
ESROBO_BODY_ARM_VECTOR_PREDICTION_HORIZON_S="${ESROBO_BODY_ARM_VECTOR_PREDICTION_HORIZON_S:-0.02}"
ESROBO_BODY_ARM_VECTOR_PREDICTION_LOOKBACK_S="${ESROBO_BODY_ARM_VECTOR_PREDICTION_LOOKBACK_S:-0.03}"
ESROBO_BODY_ARM_VECTOR_PREDICTION_MAX_VELOCITY_M_S="${ESROBO_BODY_ARM_VECTOR_PREDICTION_MAX_VELOCITY_M_S:-2.5}"
ESROBO_BODY_ARM_VECTOR_PREDICTION_MAX_DISPLACEMENT_M="${ESROBO_BODY_ARM_VECTOR_PREDICTION_MAX_DISPLACEMENT_M:-0.035}"
ESROBO_BODY_CALIBRATION_DELAY_S="${ESROBO_BODY_CALIBRATION_DELAY_S:-10.0}"
ESROBO_BODY_CALIBRATION_SAMPLE_START_S="${ESROBO_BODY_CALIBRATION_SAMPLE_START_S:-6.0}"
ESROBO_BODY_CALIBRATION_PROMPT_INTERVAL_S="${ESROBO_BODY_CALIBRATION_PROMPT_INTERVAL_S:-1.0}"
ESROBO_BODY_ENABLE_VISUALIZATION="${ESROBO_BODY_ENABLE_VISUALIZATION:-1}"
if [[ -z "${ESROBO_BODY_VISUALIZATION_OFFSET:-}" ]]; then
    if [[ "${ESROBO_BODY_USE_WAIST_FRAME,,}" == "1" || "${ESROBO_BODY_USE_WAIST_FRAME,,}" == "true" || "${ESROBO_BODY_USE_WAIST_FRAME,,}" == "yes" || "${ESROBO_BODY_USE_WAIST_FRAME,,}" == "on" ]]; then
        ESROBO_BODY_VISUALIZATION_OFFSET="0 1.1 0"
    else
        ESROBO_BODY_VISUALIZATION_OFFSET="0 1.1 1.85"
    fi
fi
ESROBO_BODY_VISUALIZATION_SCALE="${ESROBO_BODY_VISUALIZATION_SCALE:-1.0}"
ESROBO_BODY_UPPER_ARM_ANGULAR_DEADBAND_DEG="${ESROBO_BODY_UPPER_ARM_ANGULAR_DEADBAND_DEG:-0.25}"
ESROBO_BODY_FOREARM_ANGULAR_DEADBAND_DEG="${ESROBO_BODY_FOREARM_ANGULAR_DEADBAND_DEG:-0.30}"
ESROBO_USE_HAND_IMU_ORIENTATION="${ESROBO_USE_HAND_IMU_ORIENTATION:-0}"
ESROBO_HAND_ONLY_MODE="${ESROBO_HAND_ONLY_MODE:-0}"
ESROBO_HAND_ORIENTATION_INHERIT_ARM_FRAME="${ESROBO_HAND_ORIENTATION_INHERIT_ARM_FRAME:-1}"
ESROBO_HAND_IMU_RELATIVE_TO_ARM_FRAME="${ESROBO_HAND_IMU_RELATIVE_TO_ARM_FRAME:-1}"
ESROBO_HAND_IMU_MAX_STALE_TIME_S="${ESROBO_HAND_IMU_MAX_STALE_TIME_S:-0.5}"
ESROBO_HAND_SKELETON_VISUALIZATION="${ESROBO_HAND_SKELETON_VISUALIZATION:-0}"
ESROBO_HAND_SKELETON_VISUALIZATION_OFFSET="${ESROBO_HAND_SKELETON_VISUALIZATION_OFFSET:-0.55 0 0.18}"
ESROBO_HAND_SKELETON_VISUALIZATION_SCALE="${ESROBO_HAND_SKELETON_VISUALIZATION_SCALE:-1.6}"
ESROBO_HAND_SKELETON_ATTACH_TO_BODY_WRIST="${ESROBO_HAND_SKELETON_ATTACH_TO_BODY_WRIST:-1}"
ESROBO_DEBUG_XR_DATA="${ESROBO_DEBUG_XR_DATA:-0}"
ESROBO_DEBUG_PERF="${ESROBO_DEBUG_PERF:-0}"
ESROBO_DEBUG_EEF_ERROR="${ESROBO_DEBUG_EEF_ERROR:-0}"
ESROBO_DEBUG_XR_INTERVAL="${ESROBO_DEBUG_XR_INTERVAL:-60}"
ESROBO_SIM_DT="${ESROBO_SIM_DT:-0.0166666667}"
ESROBO_DECIMATION="${ESROBO_DECIMATION:-1}"
ESROBO_RENDER_INTERVAL="${ESROBO_RENDER_INTERVAL:-2}"
ISAACLAB_RENDERING_MODE="${ISAACLAB_RENDERING_MODE:-balanced}"
ESROBO_RENDER_ANTIALIASING_MODE="${ESROBO_RENDER_ANTIALIASING_MODE:-DLSS}"
ESROBO_RENDER_DENOISER="${ESROBO_RENDER_DENOISER:-1}"
ESROBO_IK_ENFORCE_VELOCITY_LIMITS="${ESROBO_IK_ENFORCE_VELOCITY_LIMITS:-0}"
ESROBO_IK_MAX_JOINT_POSITION_DELTA="${ESROBO_IK_MAX_JOINT_POSITION_DELTA:-0.105}"
ESROBO_IK_MAX_COMMAND_LEAD="${ESROBO_IK_MAX_COMMAND_LEAD:-0.25}"
ESROBO_IK_MAX_COMMAND_STEP="${ESROBO_IK_MAX_COMMAND_STEP:-0.0}"
ESROBO_IK_STATIC_TARGET_TOLERANCE="${ESROBO_IK_STATIC_TARGET_TOLERANCE:-1e-6}"
ESROBO_IK_STATIC_TARGET_HOLD_FRAMES="${ESROBO_IK_STATIC_TARGET_HOLD_FRAMES:-4}"
ESROBO_IK_STATIC_TARGET_POSITION_ERROR_M="${ESROBO_IK_STATIC_TARGET_POSITION_ERROR_M:-0.01}"
ESROBO_IK_STATIC_TARGET_ORIENTATION_ERROR_RAD="${ESROBO_IK_STATIC_TARGET_ORIENTATION_ERROR_RAD:-0.05}"
ESROBO_IK_FRAME_TASK_GAIN="${ESROBO_IK_FRAME_TASK_GAIN:-1.0}"
ESROBO_IK_FRAME_TASK_LM_DAMPING="${ESROBO_IK_FRAME_TASK_LM_DAMPING:-0.012}"
ESROBO_IK_POSITION_COST="${ESROBO_IK_POSITION_COST:-32.0}"
ESROBO_IK_ORIENTATION_COST="${ESROBO_IK_ORIENTATION_COST:-0.05}"
ESROBO_IK_ELBOW_POSITION_COST="${ESROBO_IK_ELBOW_POSITION_COST:-80.0}"
ESROBO_IK_ELBOW_ORIENTATION_COST="${ESROBO_IK_ELBOW_ORIENTATION_COST:-0.0}"
ESROBO_IK_ELBOW_FRAME_TASK_GAIN="${ESROBO_IK_ELBOW_FRAME_TASK_GAIN:-1.0}"
ESROBO_IK_ELBOW_FRAME_TASK_LM_DAMPING="${ESROBO_IK_ELBOW_FRAME_TASK_LM_DAMPING:-0.006}"
ESROBO_IK_NULLSPACE_POSTURE_COST="${ESROBO_IK_NULLSPACE_POSTURE_COST:-0.001}"
ESROBO_IK_NULLSPACE_POSTURE_GAIN="${ESROBO_IK_NULLSPACE_POSTURE_GAIN:-0.001}"
ESROBO_IK_NULLSPACE_POSTURE_LM_DAMPING="${ESROBO_IK_NULLSPACE_POSTURE_LM_DAMPING:-0.5}"
ESROBO_ARM_EFFORT_LIMIT_SIM="${ESROBO_ARM_EFFORT_LIMIT_SIM:-3500.0}"
ESROBO_ARM_VELOCITY_LIMIT_SIM="${ESROBO_ARM_VELOCITY_LIMIT_SIM:-180.0}"
ESROBO_ARM_STIFFNESS="${ESROBO_ARM_STIFFNESS:-8800.0}"
ESROBO_ARM_DAMPING="${ESROBO_ARM_DAMPING:-320.0}"
ESROBO_ARM_VELOCITY_FEEDFORWARD_GAIN="${ESROBO_ARM_VELOCITY_FEEDFORWARD_GAIN:-0.6}"
ESROBO_ARM_VELOCITY_FEEDFORWARD_MAX_RAD_S="${ESROBO_ARM_VELOCITY_FEEDFORWARD_MAX_RAD_S:-8.0}"
ESROBO_ARM_VELOCITY_FEEDFORWARD_DEADBAND_RAD="${ESROBO_ARM_VELOCITY_FEEDFORWARD_DEADBAND_RAD:-0.0015}"
ESROBO_ARM_VELOCITY_FEEDFORWARD_START_SPEED_M_S="${ESROBO_ARM_VELOCITY_FEEDFORWARD_START_SPEED_M_S:-0.12}"
ESROBO_ARM_VELOCITY_FEEDFORWARD_FULL_SPEED_M_S="${ESROBO_ARM_VELOCITY_FEEDFORWARD_FULL_SPEED_M_S:-0.75}"
ESROBO_WAIST_HEAD_EFFORT_LIMIT_SIM="${ESROBO_WAIST_HEAD_EFFORT_LIMIT_SIM:-2500.0}"
ESROBO_WAIST_HEAD_VELOCITY_LIMIT_SIM="${ESROBO_WAIST_HEAD_VELOCITY_LIMIT_SIM:-20.0}"
ESROBO_WAIST_HEAD_STIFFNESS="${ESROBO_WAIST_HEAD_STIFFNESS:-8000.0}"
ESROBO_WAIST_HEAD_DAMPING="${ESROBO_WAIST_HEAD_DAMPING:-800.0}"
case "${ESROBO_RENDER_DENOISER,,}" in
    1|true|yes|on)
        ESROBO_RENDER_DENOISER_SETTING=true
        ;;
    0|false|no|off)
        ESROBO_RENDER_DENOISER_SETTING=false
        ;;
    *)
        echo "Unknown ESROBO_RENDER_DENOISER=${ESROBO_RENDER_DENOISER}; using 1."
        ESROBO_RENDER_DENOISER=1
        ESROBO_RENDER_DENOISER_SETTING=true
        ;;
esac
DEFAULT_KIT_ARGS="--/persistent/physics/visualizationDisplayJoints=0 --/rtx/post/motionblur/enabled=false --/rtx/post/motionblur/exposureFraction=0 --/rtx/post/motionblur/maxBlurDiameterFraction=0 --/rtx/post/dof/enabled=false --/rtx-transient/dlssg/enabled=false --/rtx-transient/dldenoiser/enabled=${ESROBO_RENDER_DENOISER_SETTING}"
ISAACLAB_KIT_ARGS="${ISAACLAB_KIT_ARGS-${DEFAULT_KIT_ARGS}}"

if [[ -f "${HOME}/anaconda3/etc/profile.d/conda.sh" ]]; then
    # shellcheck source=/dev/null
    source "${HOME}/anaconda3/etc/profile.d/conda.sh"
elif [[ -f "${HOME}/miniconda3/etc/profile.d/conda.sh" ]]; then
    # shellcheck source=/dev/null
    source "${HOME}/miniconda3/etc/profile.d/conda.sh"
fi

conda activate "${ISAACLAB_ENV_NAME}"
if [[ "${TERM:-}" == "dumb" || -z "${TERM:-}" ]]; then
    export TERM=xterm-256color
fi
export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH:-}"

export ESROBO_BODY_UDP_HOST
export ESROBO_BODY_UDP_PORT
export ESROBO_BODY_SWAP_LEFT_RIGHT_TARGETS
export ESROBO_BODY_POSITION_DELTA_SIGNS
export ESROBO_BODY_RETARGETING_MODE
export ESROBO_BODY_ARM_VECTOR_POSITION_MODE
export ESROBO_ENABLE_ELBOW_IK_TASKS
export ESROBO_WRIST_ONLY_IK
export ESROBO_BODY_USE_WAIST_FRAME
export ESROBO_BODY_REQUIRE_CALIBRATION
export ESROBO_BODY_AUTO_START_REFERENCE
export ESROBO_BODY_AUTO_START_REFERENCE_DELAY_S
export ESROBO_BODY_AUTO_START_REFERENCE_SAMPLE_START_S
export ESROBO_BODY_AUTO_START_REFERENCE_MAX_STD_M
export ESROBO_BODY_AUTO_START_REFERENCE_MIN_SAMPLES
export ESROBO_BODY_AUTO_START_REFERENCE_REQUIRE_WAIST
export ESROBO_BODY_ARM_VECTOR_MAX_REACH
export ESROBO_BODY_ARM_VECTOR_PREDICTION_HORIZON_S
export ESROBO_BODY_ARM_VECTOR_PREDICTION_LOOKBACK_S
export ESROBO_BODY_ARM_VECTOR_PREDICTION_MAX_VELOCITY_M_S
export ESROBO_BODY_ARM_VECTOR_PREDICTION_MAX_DISPLACEMENT_M
export ESROBO_BODY_CALIBRATION_DELAY_S
export ESROBO_BODY_CALIBRATION_SAMPLE_START_S
export ESROBO_BODY_CALIBRATION_PROMPT_INTERVAL_S
export ESROBO_BODY_ENABLE_VISUALIZATION
export ESROBO_BODY_VISUALIZATION_OFFSET
export ESROBO_BODY_VISUALIZATION_SCALE
export ESROBO_BODY_UPPER_ARM_ANGULAR_DEADBAND_DEG
export ESROBO_BODY_FOREARM_ANGULAR_DEADBAND_DEG
export ESROBO_USE_HAND_IMU_ORIENTATION
export ESROBO_HAND_ONLY_MODE
export ESROBO_HAND_ORIENTATION_INHERIT_ARM_FRAME
export ESROBO_HAND_IMU_RELATIVE_TO_ARM_FRAME
export ESROBO_HAND_IMU_MAX_STALE_TIME_S
export ESROBO_HAND_SKELETON_VISUALIZATION
export ESROBO_HAND_SKELETON_VISUALIZATION_OFFSET
export ESROBO_HAND_SKELETON_VISUALIZATION_SCALE
export ESROBO_HAND_SKELETON_ATTACH_TO_BODY_WRIST
export ESROBO_DEBUG_EEF_ERROR
export ESROBO_HAND_IMU_SOURCE_TO_ROBOT_ROTATION="${ESROBO_HAND_IMU_SOURCE_TO_ROBOT_ROTATION:-}"
export ESROBO_SIM_DT
export ESROBO_DECIMATION
export ESROBO_RENDER_INTERVAL
export ESROBO_RENDER_ANTIALIASING_MODE
export ESROBO_RENDER_DENOISER
export ESROBO_IK_MAX_JOINT_POSITION_DELTA
export ESROBO_IK_MAX_COMMAND_LEAD
export ESROBO_IK_MAX_COMMAND_STEP
export ESROBO_IK_STATIC_TARGET_TOLERANCE
export ESROBO_IK_STATIC_TARGET_HOLD_FRAMES
export ESROBO_IK_STATIC_TARGET_POSITION_ERROR_M
export ESROBO_IK_STATIC_TARGET_ORIENTATION_ERROR_RAD
export ESROBO_IK_ENFORCE_VELOCITY_LIMITS
export ESROBO_IK_FRAME_TASK_GAIN
export ESROBO_IK_FRAME_TASK_LM_DAMPING
export ESROBO_IK_POSITION_COST
export ESROBO_IK_ORIENTATION_COST
export ESROBO_IK_ELBOW_POSITION_COST
export ESROBO_IK_ELBOW_ORIENTATION_COST
export ESROBO_IK_ELBOW_FRAME_TASK_GAIN
export ESROBO_IK_ELBOW_FRAME_TASK_LM_DAMPING
export ESROBO_IK_NULLSPACE_POSTURE_COST
export ESROBO_IK_NULLSPACE_POSTURE_GAIN
export ESROBO_IK_NULLSPACE_POSTURE_LM_DAMPING
export ESROBO_ARM_EFFORT_LIMIT_SIM
export ESROBO_ARM_VELOCITY_LIMIT_SIM
export ESROBO_ARM_STIFFNESS
export ESROBO_ARM_DAMPING
export ESROBO_ARM_VELOCITY_FEEDFORWARD_GAIN
export ESROBO_ARM_VELOCITY_FEEDFORWARD_MAX_RAD_S
export ESROBO_ARM_VELOCITY_FEEDFORWARD_DEADBAND_RAD
export ESROBO_ARM_VELOCITY_FEEDFORWARD_START_SPEED_M_S
export ESROBO_ARM_VELOCITY_FEEDFORWARD_FULL_SPEED_M_S
export ESROBO_WAIST_HEAD_EFFORT_LIMIT_SIM
export ESROBO_WAIST_HEAD_VELOCITY_LIMIT_SIM
export ESROBO_WAIST_HEAD_STIFFNESS
export ESROBO_WAIST_HEAD_DAMPING
export DUAL_ARM_TELEOP_ROOT="${DUAL_ARM_TELEOP_ROOT:-${ROOT_DIR}}"
export PYTHONPATH="${ROOT_DIR}/src:${PYTHONPATH:-}"
export PYTHONUNBUFFERED=1

echo "Starting ESROBO IsaacLab simulation without XR rendering/streaming."
echo "Task: ${TASK}"
echo "Listening for body-tracking UDP on ${ESROBO_BODY_UDP_HOST}:${ESROBO_BODY_UDP_PORT}."
echo "Wrist target mapping swap: ESROBO_BODY_SWAP_LEFT_RIGHT_TARGETS=${ESROBO_BODY_SWAP_LEFT_RIGHT_TARGETS}."
echo "Waist-relative body frame: ESROBO_BODY_USE_WAIST_FRAME=${ESROBO_BODY_USE_WAIST_FRAME}."
echo "Robot-frame position delta signs: ESROBO_BODY_POSITION_DELTA_SIGNS=${ESROBO_BODY_POSITION_DELTA_SIGNS}."
echo "Body retargeting mode: ESROBO_BODY_RETARGETING_MODE=${ESROBO_BODY_RETARGETING_MODE}."
echo "Arm-vector position mode: ESROBO_BODY_ARM_VECTOR_POSITION_MODE=${ESROBO_BODY_ARM_VECTOR_POSITION_MODE}."
echo "Elbow IK tasks: ESROBO_ENABLE_ELBOW_IK_TASKS=${ESROBO_ENABLE_ELBOW_IK_TASKS}."
echo "Wrist-only IK: ESROBO_WRIST_ONLY_IK=${ESROBO_WRIST_ONLY_IK}; when enabled, arm joints 1-4 are locked and only joints 5-7 control hand orientation."
echo "Arm-vector max robot reach: ESROBO_BODY_ARM_VECTOR_MAX_REACH=${ESROBO_BODY_ARM_VECTOR_MAX_REACH}m."
echo "Arm-vector prediction: horizon=${ESROBO_BODY_ARM_VECTOR_PREDICTION_HORIZON_S}s, lookback=${ESROBO_BODY_ARM_VECTOR_PREDICTION_LOOKBACK_S}s, max_velocity=${ESROBO_BODY_ARM_VECTOR_PREDICTION_MAX_VELOCITY_M_S}m/s, max_displacement=${ESROBO_BODY_ARM_VECTOR_PREDICTION_MAX_DISPLACEMENT_M}m."
echo "Skeleton visualization: ESROBO_BODY_ENABLE_VISUALIZATION=${ESROBO_BODY_ENABLE_VISUALIZATION}, offset='${ESROBO_BODY_VISUALIZATION_OFFSET}', scale=${ESROBO_BODY_VISUALIZATION_SCALE}."
echo "SenseGlove IMU absolute hand orientation: ESROBO_USE_HAND_IMU_ORIENTATION=${ESROBO_USE_HAND_IMU_ORIENTATION}, max_stale=${ESROBO_HAND_IMU_MAX_STALE_TIME_S}s."
echo "Hand orientation inherits the arm frame when IMU is unavailable: ESROBO_HAND_ORIENTATION_INHERIT_ARM_FRAME=${ESROBO_HAND_ORIENTATION_INHERIT_ARM_FRAME}."
echo "SenseGlove IMU is interpreted relative to the synchronized arm frame: ESROBO_HAND_IMU_RELATIVE_TO_ARM_FRAME=${ESROBO_HAND_IMU_RELATIVE_TO_ARM_FRAME}."
echo "SenseGlove-only mode: ESROBO_HAND_ONLY_MODE=${ESROBO_HAND_ONLY_MODE}; hand skeleton=${ESROBO_HAND_SKELETON_VISUALIZATION}, attach_to_body_wrist=${ESROBO_HAND_SKELETON_ATTACH_TO_BODY_WRIST}, fallback_offset='${ESROBO_HAND_SKELETON_VISUALIZATION_OFFSET}', scale=${ESROBO_HAND_SKELETON_VISUALIZATION_SCALE}."
echo "Body calibration required: ESROBO_BODY_REQUIRE_CALIBRATION=${ESROBO_BODY_REQUIRE_CALIBRATION}."
if [[ "${ESROBO_BODY_REQUIRE_CALIBRATION,,}" == "1" || "${ESROBO_BODY_REQUIRE_CALIBRATION,,}" == "true" || "${ESROBO_BODY_REQUIRE_CALIBRATION,,}" == "yes" || "${ESROBO_BODY_REQUIRE_CALIBRATION,,}" == "on" ]]; then
    echo "Two-pose calibration: ${ESROBO_BODY_CALIBRATION_DELAY_S}s per pose; valid samples record from ${ESROBO_BODY_CALIBRATION_SAMPLE_START_S}s to ${ESROBO_BODY_CALIBRATION_DELAY_S}s."
    echo "Calibration flow: 1) arms naturally down, 2) arms raised/stretched horizontally in front of chest, then wait for 'Calibration locked'."
else
    if [[ "${ESROBO_BODY_ARM_VECTOR_POSITION_MODE}" == "segment_direction_absolute" || "${ESROBO_BODY_ARM_VECTOR_POSITION_MODE}" == "segment_direction" ]]; then
        echo "Body calibration is disabled; absolute arm-vector mode uses live full-body shoulder/elbow/wrist frames directly."
        echo "Absolute segment mode: robot arms follow PICO absolute shoulder->elbow and elbow->wrist directions after source-to-robot rotation."
    elif [[ "${ESROBO_BODY_AUTO_START_REFERENCE,,}" == "1" || "${ESROBO_BODY_AUTO_START_REFERENCE,,}" == "true" || "${ESROBO_BODY_AUTO_START_REFERENCE,,}" == "yes" || "${ESROBO_BODY_AUTO_START_REFERENCE,,}" == "on" ]]; then
        echo "Body calibration is disabled; automatic startup reference is enabled."
        echo "Auto reference: hold neutral/still for ${ESROBO_BODY_AUTO_START_REFERENCE_DELAY_S}s; valid samples record from ${ESROBO_BODY_AUTO_START_REFERENCE_SAMPLE_START_S}s; max_std=${ESROBO_BODY_AUTO_START_REFERENCE_MAX_STD_M}m; min_samples=${ESROBO_BODY_AUTO_START_REFERENCE_MIN_SAMPLES}; require_waist=${ESROBO_BODY_AUTO_START_REFERENCE_REQUIRE_WAIST}."
    else
        echo "Body calibration is disabled; arm_vector uses live full-body shoulder/elbow/wrist frames directly."
    fi
fi
echo "Sim/control timing: sim_dt=${ESROBO_SIM_DT}, decimation=${ESROBO_DECIMATION}, render_interval=${ESROBO_RENDER_INTERVAL}, rendering_mode=${ISAACLAB_RENDERING_MODE}, anti_aliasing=${ESROBO_RENDER_ANTIALIASING_MODE}, denoiser=${ESROBO_RENDER_DENOISER_SETTING}."
echo "Posture stabilization: upper_arm_deadband=${ESROBO_BODY_UPPER_ARM_ANGULAR_DEADBAND_DEG}deg, forearm_deadband=${ESROBO_BODY_FOREARM_ANGULAR_DEADBAND_DEG}deg."
echo "Teleop response: ik_urdf_velocity_limits=${ESROBO_IK_ENFORCE_VELOCITY_LIMITS}, ik_delta=${ESROBO_IK_MAX_JOINT_POSITION_DELTA}, ik_command_lead=${ESROBO_IK_MAX_COMMAND_LEAD}, ik_command_step=${ESROBO_IK_MAX_COMMAND_STEP}, ik_static_hold=${ESROBO_IK_STATIC_TARGET_HOLD_FRAMES}frames@${ESROBO_IK_STATIC_TARGET_TOLERANCE}/position_error<=${ESROBO_IK_STATIC_TARGET_POSITION_ERROR_M}m/orientation_error<=${ESROBO_IK_STATIC_TARGET_ORIENTATION_ERROR_RAD}rad, wrist_gain/lm=${ESROBO_IK_FRAME_TASK_GAIN}/${ESROBO_IK_FRAME_TASK_LM_DAMPING}, wrist_cost_pos/orient=${ESROBO_IK_POSITION_COST}/${ESROBO_IK_ORIENTATION_COST}, elbow_gain/lm=${ESROBO_IK_ELBOW_FRAME_TASK_GAIN}/${ESROBO_IK_ELBOW_FRAME_TASK_LM_DAMPING}, elbow_cost_pos/orient=${ESROBO_IK_ELBOW_POSITION_COST}/${ESROBO_IK_ELBOW_ORIENTATION_COST}, nullspace_cost/gain=${ESROBO_IK_NULLSPACE_POSTURE_COST}/${ESROBO_IK_NULLSPACE_POSTURE_GAIN}, arm_vel=${ESROBO_ARM_VELOCITY_LIMIT_SIM}, arm_effort=${ESROBO_ARM_EFFORT_LIMIT_SIM}, arm_kd=${ESROBO_ARM_STIFFNESS}/${ESROBO_ARM_DAMPING}, arm_velocity_ff_gain/max/deadband=${ESROBO_ARM_VELOCITY_FEEDFORWARD_GAIN}/${ESROBO_ARM_VELOCITY_FEEDFORWARD_MAX_RAD_S}/${ESROBO_ARM_VELOCITY_FEEDFORWARD_DEADBAND_RAD}, arm_velocity_ff_speed_start/full=${ESROBO_ARM_VELOCITY_FEEDFORWARD_START_SPEED_M_S}/${ESROBO_ARM_VELOCITY_FEEDFORWARD_FULL_SPEED_M_S}m/s, waist_head_hold_vel/effort=${ESROBO_WAIST_HEAD_VELOCITY_LIMIT_SIM}/${ESROBO_WAIST_HEAD_EFFORT_LIMIT_SIM}, waist_head_hold_kd=${ESROBO_WAIST_HEAD_STIFFNESS}/${ESROBO_WAIST_HEAD_DAMPING}."
echo "Verbose teleop debug: xr_data=${ESROBO_DEBUG_XR_DATA} perf=${ESROBO_DEBUG_PERF} eef_error=${ESROBO_DEBUG_EEF_ERROR} interval=${ESROBO_DEBUG_XR_INTERVAL}."
echo "Kit args: ${ISAACLAB_KIT_ARGS}"
echo "Run scripts/run_xrobotoolkit_body_to_esrobo_teleop_bridge.sh in another terminal to provide XRoboToolkit full-body shoulder/elbow/wrist targets."
echo "Optional: run scripts/run_senseglove_to_esrobo_hand_bridge.sh to provide ESROBO active hand-joint targets and calibrated hand IMU orientation on the same UDP port."
echo

cd "${ISAACLAB_DIR}"
ISAACLAB_ARGS=(
    -p "${ROOT_DIR}/scripts/esrobo_teleop_se3_agent.py"
    --task "${TASK}"
    --teleop_device bodytracking_udp
    --num_envs 1
    --device "${DEVICE}"
    --rendering_mode "${ISAACLAB_RENDERING_MODE}"
    --kit_args="${ISAACLAB_KIT_ARGS}"
    --enable_pinocchio
)

if [[ "${ESROBO_DEBUG_XR_DATA}" == "1" ]]; then
    ISAACLAB_ARGS+=(--debug_xr_data --debug_xr_interval "${ESROBO_DEBUG_XR_INTERVAL}")
fi
if [[ "${ESROBO_DEBUG_PERF}" == "1" ]]; then
    ISAACLAB_ARGS+=(--debug_perf --debug_xr_interval "${ESROBO_DEBUG_XR_INTERVAL}")
fi
if [[ "${ESROBO_DEBUG_EEF_ERROR}" == "1" ]]; then
    ISAACLAB_ARGS+=(--debug_eef_error --debug_xr_interval "${ESROBO_DEBUG_XR_INTERVAL}")
fi

exec ./isaaclab.sh "${ISAACLAB_ARGS[@]}" "$@"
